POST  http://localhost:5000/candidate
Content-Type: application/json

{
    
    "name":"Rakesh",
    "age":"40",
    "gender":"Male",
    "constituency":"New Delhi",
    "political_party":"B.J.P",
    "consti_id":"1"
}